---
# tasks file for apache_lb
# update apt repository
- name: Update and install Apache
  become: true
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Install development package for libxml2 library
  become: true
  apt:
    name: libxml2-dev
    state: present
    update_cache: yes

# Enable apache modules 
- name: Enable Apache modules for load balancing
  become: true
  command: "a2enmod {{ item }}"
  loop:
    - proxy
    - proxy_http
    - proxy_balancer
    - lbmethod_bytraffic
    - headers
  notify: restart apache

# Configure local dns
- name: Update /etc/hosts with backend server hostnames
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
    create: yes
  loop: "{{ web_servers_hosts }}"
  tags:
    - dns

# Configure load balancer
- name: Create load balancing configuration
  become: true
  template:
    src: webserver-lb.conf.j2
    dest: /etc/apache2/sites-available/webserver-lb.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache
  tags:
    - apache

# enable the webserver-lb config
- name: Enable webserver load balancer configuration
  become: true
  command: a2ensite webserver-lb.conf
  notify: restart apache
  tags:
    - apache

# disable the default config
- name: Disable default Apache site configuration
  become: true
  command: a2dissite 000-default.conf
  notify: restart apache
  tags:
    - apache



# Conditional logic to enable or disable apache lb

- name: Ensure Apache is started for UAT if enabled
  service:
    name: apache2
    state: started
    enabled: true
  when:
    - enable_apache_lb
    - load_balancer_is_required

- name: Stop Apache if not required
  service:
    name: apache2
    state: stopped
  when:
    - not enable_apache_lb
    - load_balancer_is_required
