---
# tasks file for nginx_lb
- name: Ensure Nginx is started for UAT if enabled
  service:
    name: nginx
    state: started
    enabled: true
  become: true
  when:
    - enable_nginx_lb
    - load_balancer_is_required
    - lb_type == "nginx"

- name: Stop Nginx if not required
  service:  
    name: nginx
    state: stopped
  become: true
  when:
    - not enable_nginx_lb
    - load_balancer_is_required
    - lb_type == "nginx"

- name: Configure Nginx Load Balancer if enabled
  template:
    src: "nginx-lb.conf.j2"
    dest: "/etc/nginx/conf.d/load-balancer.conf"
    mode: '0644'
  become: true
  when:
    - enable_nginx_lb
    - load_balancer_is_required
    - lb_type == "nginx"
  notify:
    - reload nginx

- name: Remove default nginx site # often solves 404 error
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  when: lb_type == "nginx"
  notify: reload nginx
