 [nfs]
 172.31.39.177 ansible_ssh_user=ec2-user

 [webservers]
 172.31.32.255 ansible_ssh_user=ec2-user
 172.31.35.27 ansible_ssh_user=ec2-user
 172.31.32.34 ansible_ssh_user=ec2-user

 [db]
 172.31.38.76 ansible_ssh_user=ubuntu

 [lb]
 172.31.46.249 ansible_ssh_user=ubuntu # Nginx
 172.31.16.59 ansible_ssh_user=ubuntu # Apache

 [db:vars]
 env_vars_file=../env-vars/dev.yml  # Specify environment variables file for database setup
