pipeline {
    agent any
    stages {
        stage('SCM checkout') {
            steps {
                git branch: 'main',
                    credentialsId: '[github-credentials id]',
                    url: '[github url]'
            }
        }
        stage('Execute Ansible') {
            steps {
                ansiblePlaybook credentialsId: 'private-key',
                    disableHostKeyChecking: true,
                    installation: 'ansible',
                    inventory: 'inventory/dev.yml',
                    playbook: 'static-assignments/common.yml',
                    vaultTmpPath: ''
            }
        }
    }
}
