pipeline {
    agent any
    stages {
        stage('SCM checkout') {
            steps {
                git branch: 'main',
                    credentialsId: '74ca1016-facc-42b7-8442-e10e307d8f27',
                    url: 'https://github.com/laraadeboye/ansible-config-mgt'
            }
        }
        stage('Execute Ansible') {
            steps {
                ansiblePlaybook credentialsId: 'private-key',
                    disableHostKeyChecking: true,
                    installation: 'ansible',
                    inventory: 'inventory/dev.yml',
                    playbook: 'static-assignments/common.yml',
                    vaultTmpPath: ''
            }
        }
    }
}
