---
# tasks file for php

- name: Update apt cache (for Debian/Ubuntu systems)
  become: yes
  apt:
    update_cache: yes

- name: Install software-properties-common
  become: yes
  apt:
    name: software-properties-common
    state: present

- name: Add Ondřej Surý PPA for PHP
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update apt cache after adding PPA
  become: yes
  apt:
    update_cache: yes

- name: Remove existing PHP packages
  become: yes
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - php*
    - libapache2-mod-php*
  ignore_errors: yes

- name: Autoremove any leftover PHP dependencies
  become: yes
  command: apt-get autoremove -y
  changed_when: false

- name: Install PHP and dependencies
  become: yes
  package:
    name: "{{ php_packages }}"
    state: present

- name: Download Composer installer
  become: yes
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: '0755'
    validate_certs: yes  
  

- name: Fetch Composer installer SHA-384 hash
  uri:
    url: https://composer.github.io/installer.sig
    return_content: yes  
  register: composer_hash
  changed_when: false

- name: Verify Composer installer
  become: yes
  block:
    - name: Verify Composer installer
      command: >
        php -r "
        if (hash_file('SHA384', '/tmp/composer-setup.php') === '{{ composer_hash.content }}') {
            echo 'Installer verified';
            exit(0);
        } else {
            echo 'Installer corrupt';
            exit(1);
        }"
      changed_when: false
      register: composer_verification


- name: Install Composer globally
  become: yes
  command: >
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Remove Composer installer
  become: yes
  file:
    path: /tmp/composer-setup.php
    state: absent

- name: Install Xdebug
  become: yes
  apt:
    name: php{{ php_version }}-xdebug
    state: present

- name: Configure PHP for code coverage
  become: yes
  lineinfile:
    path: "/etc/php/{{ php_version }}/cli/php.ini"
    line: "xdebug.mode=coverage"
    state: present
